# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kupid < Formula
  desc "Pick any Deep schema fields, create your own table view of Kubernetes TUI."
  homepage "https://github.com/flavono123/kupid"
  version "0.0.9-alpha"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flavono123/kupid/releases/download/v0.0.9-alpha/kupid_v0.0.9-alpha_darwin_amd64.tar.gz"
      sha256 "0d859786a03905af64b6fff93b4940329b0bf8c7ad658fbd5bd682b58e9b7f1e"

      def install
        bin.install "kupid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flavono123/kupid/releases/download/v0.0.9-alpha/kupid_v0.0.9-alpha_darwin_arm64.tar.gz"
      sha256 "93bc5c36fae842d854448963774071ac46ed9e48cfa4e86d90d967fc43bea0e7"

      def install
        bin.install "kupid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flavono123/kupid/releases/download/v0.0.9-alpha/kupid_v0.0.9-alpha_linux_amd64.tar.gz"
        sha256 "de0bf4989215559a0e6d1e8caf1ad84fa7d4fc70982324ef8e09f97a1f7fa865"

        def install
          bin.install "kupid"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flavono123/kupid/releases/download/v0.0.9-alpha/kupid_v0.0.9-alpha_linux_arm64.tar.gz"
        sha256 "f0d6f4a169debf494c1021fdacbc04914b621284df772693d75997521d36adfd"

        def install
          bin.install "kupid"
        end
      end
    end
  end
end
