# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kupid < Formula
  desc "Pick any Deep schema fields, create your own table view of Kubernetes TUI."
  homepage "https://github.com/flavono123/kupid"
  version "0.0.10-alpha"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flavono123/kupid/releases/download/v0.0.10-alpha/kupid_v0.0.10-alpha_darwin_amd64.tar.gz"
      sha256 "4a9928fe48926cfd00336a9cc8bc07c4b8a863fce2c1c1bda7bfe674f9377c48"

      def install
        bin.install "kupid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flavono123/kupid/releases/download/v0.0.10-alpha/kupid_v0.0.10-alpha_darwin_arm64.tar.gz"
      sha256 "4049602de4b44e7439319b71c183c2b474f84a57e12b718d472698aea767a7bd"

      def install
        bin.install "kupid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flavono123/kupid/releases/download/v0.0.10-alpha/kupid_v0.0.10-alpha_linux_amd64.tar.gz"
        sha256 "6eade6170a48688b5b791e46a21277dfab3c4be7727b04215e1bcbeb7de83a63"

        def install
          bin.install "kupid"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flavono123/kupid/releases/download/v0.0.10-alpha/kupid_v0.0.10-alpha_linux_arm64.tar.gz"
        sha256 "e9253664874c2a5831543587147fdd8e08bbfb890cf74d1e7f1abbbac9727b16"

        def install
          bin.install "kupid"
        end
      end
    end
  end
end
